theme: jekyll-theme-slate
title: aerolab – Akademischer Flugzeugmodellbau an der TU Berlin
description: Die Projektwerkstatt AeroLab hat das Ziel, den akademischen Flugzeugmodellbau an der TU Berlin zu fördern und Studierenden Grundkenntnisse des Flugzeugbaus zu vermitteln.
